### ISSUE TITLE
Is it possible to group metrics by type when using a JmxReporter?

### ISSUE THREAD

**Issue by HenriqueMCastro** [palominolabs/metrics-guice#25]
I have several counters (non metrics-guice) grouped by type in JMX (for example, all the counters for servlets would be under the type servlets) and I was trying to put new metrics-guice counters grouped under the same type. 
But I haven't found a way to do that. The Timed annotation (for example) only has the field name. So I can't specify the type for JMX. 

Is there anyway I can use metrics-guice and group metrics in JMX by type? Or would I have to change the annotation and add a type field and then use that type when registering the metric with JMX?

**Comment by marshallpierce** [comment]
I'm not sure what you mean when you say "grouped by type". Can you give me an example?

In general, this sort of limitation is one of the issues with "do it by magic" things like metrics-guice. Furthermore, metrics-guice as it currently stands is not very configurable, and I haven't changed that since I took over maintenance. I took a different approach to configurability in https://bitbucket.org/marshallpierce/jersey2-metrics, and I'd be happy to give users of this library the same level of control, so if we can figure out a clean way to encapsulate the flexibility to configure what you're after, I'm all for it.

**Comment by HenriqueMCastro** [comment]
When I said "grouped by type" I was talking about the hierarchy of JMX beans. 
For example:
[https://visualvm.java.net/images/docs/remote-jmx-mbeans.png](url)
You can see that the domain is "DefaulDomain", the type is "SimpleDynamic" and the name is "1". Currently there is no way to specify the type so when seeing the jmx beans in visualvm (or any similar tool) all the metrics (one jmx bean for each metric) will all be at the same level. 
So if you have a lot of metrics you will have a big list of metrics which will be confusing. So normally you group related jmx beans under the same type (like a folder). 

The domain can be specified when you create the JmxReporter (com.codahale.metrics.JmxReporter) and the name is specified in the annotation. 

Looking at the code seems like the limitation is in the JmxReporter and not in guice-metrics. The JmxReporter register a listener and every time a metrics is added it register the metric as a jmx bean but it has a layer around the name of the jmxBean (ObjectName) and doesn't let you pass your own ObjectName.

So I guess if I wanted to specify a type for my jmx beans I would have to go to the project metrics-core.

**Comment by marshallpierce** [comment]
Ah, gotcha. I was wondering how the metric name specified by metrics-guice was going to end up as a type... :)
